/* Generated by AN DISI Unibo */ 
package it.unibo.caller2

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Caller2 ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		 
				var odd         = true
				
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("caller2 request cmd ")
					}
					 transition( edgeName="goto",targetState="waitForInput", cond=doswitch() )
				}	 
				state("waitForInput") { //this:State
					action { //it:State
						println("caller2 waiting ... ")
					}
					 transition(edgeName="t00",targetState="handleAlarm",cond=whenEvent("sonarAlarm"))
				}	 
				state("handleAlarm") { //this:State
					action { //it:State
						println("---------------------------------------------------")
						println("$name in ${currentState.stateName} | $currentMsg")
						println("---------------------------------------------------")
					}
					 transition( edgeName="goto",targetState="switchedLed", cond=doswitch() )
				}	 
				state("switchedLed") { //this:State
					action { //it:State
						if(  odd  
						 ){updateResourceRep( "ledCmdOn"  
						)
						forward("ledCmd", "ledCmd(on)" ,"led" ) 
						}
						else
						 {updateResourceRep( "ledCmdOff"  
						 )
						 forward("ledCmd", "ledCmd(off)" ,"led" ) 
						 }
						 odd = !odd  
					}
					 transition( edgeName="goto",targetState="waitForInput", cond=doswitch() )
				}	 
			}
		}
}
