/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unibo.boundaryWalk;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import static org.junit.Assert.assertTrue;

    public class BoundaryWalkTest {


        private MoveVirtualRobot appl;
        private String moves="";

        @Before
        public void systemSetUp() {
            System.out.println("TestMoveVirtualRobot | setUp: robot should be at HOME-DOWN ");
            appl = new MoveVirtualRobot();
        }

        @After
        public void terminate() {
            System.out.println("%%%  TestMoveVirtualRobot |  terminates ");
        }

     /*   @Test
        public void testMovesNoFailing() {
            System.out.println("TestMoveVirtualRobot | testWork ");
            boolean moveFailed = appl.moveLeft(300);
            assertTrue(!moveFailed);
            moveFailed = appl.moveRight(1000);    //back to DOWN
            assertTrue(!moveFailed);
            moveFailed = appl.moveStop(100);
            assertTrue(!moveFailed);
        }

        @Test
        public void testMoveForwardNoHit() {
            System.out.println("TestMoveVirtualRobot | testMoveForward ");
            boolean moveFailed = appl.moveForward(600);
            assertTrue(!moveFailed);
            moveFailed = appl.moveBackward(600);  //back to home
            assertTrue(!moveFailed);
        }

        @Test
        public void testMoveForwardHit() {
            System.out.println("TestMoveVirtualRobot | testMoveForward ");
            boolean moveFailed = appl.moveForward(1600);
            assertTrue(moveFailed);
            moveFailed = appl.moveBackward(1600);       //back to home
            assertTrue(moveFailed);
        }*/

        @Test
        public void testBoundaryWalk(){
            System.out.println("TestBoundaryWalk | testMove ");

            boolean moveFailed=true;
            for(int i=0; i<4;i++){
//                if (!moveFailed) {
                    while (moveFailed!=true) {
                        moveFailed= appl.moveForward(100);
                        moves = moves + "w";
                        System.out.println("TestBoundaryWalkString | testMove " + moves);
                        //assertTrue(moveFailed);

                    }
               // } else {
                    moveFailed = appl.moveLeft(500);
                    moves = moves + "l";
                    System.out.println("TestBoundaryWalkString | testMove " + moves);
                }
            }



    }

