/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unibo.boundarywalker;

public class App {
    public String doBoundary () {
        return "Hello World!";
    }

    public static void main(String[] args) {

    }
}
